// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBen9zsgvvUHUe7UjIXrj8UD-MxDhtHmRY',
    appId: '1:100022440174:web:1ef83dfb72ffff5f1e23ff',
    messagingSenderId: '100022440174',
    projectId: 'financial-keeper',
    authDomain: 'financial-keeper.firebaseapp.com',
    storageBucket: 'financial-keeper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWLWf8FlcOLPFrd2XeleWNo_xS-etA4fs',
    appId: '1:100022440174:android:44730c7ebfb908af1e23ff',
    messagingSenderId: '100022440174',
    projectId: 'financial-keeper',
    storageBucket: 'financial-keeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pyCHQ3jAhPKv1D5uVLAruQa3W5w7avo',
    appId: '1:100022440174:ios:6c855c3131a35c0e1e23ff',
    messagingSenderId: '100022440174',
    projectId: 'financial-keeper',
    storageBucket: 'financial-keeper.firebasestorage.app',
    iosBundleId: 'com.example.financialkeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBen9zsgvvUHUe7UjIXrj8UD-MxDhtHmRY',
    appId: '1:100022440174:web:0df9656d1de8c2ce1e23ff',
    messagingSenderId: '100022440174',
    projectId: 'financial-keeper',
    authDomain: 'financial-keeper.firebaseapp.com',
    storageBucket: 'financial-keeper.firebasestorage.app',
  );
}
